### PR TITLE
[expand button]: change expand icon

### PR DESCRIPTION
**Pull request by legomushroom**
The PR adds the new expand/collapse icon for open toggle button: // @davidkpiano @philliphoff @avanderhoorn 

hud-new

### CODE REVIEW

**Comment by legomushroom** [comment]
Issue: https://github.com/Glimpse/Glimpse.Client.Hud/issues/133

**Comment by davidkpiano** [comment]
LGTM!

**Comment by philliphoff** [comment]
Yes! So much better! LGTM.

**Review by mike-kaufman — APPROVED** [review]

**Comment by legomushroom** [comment]
@mike-kaufman please merge when you think the right time with the build is.

**Review by davidkpiano — APPROVED** [review]

**Pull request merged**
