### PR TITLE
Adding status icons

### PR DESCRIPTION
**Pull request by davidkpiano**
screen shot 2017-06-26 at 6 07 17 pm

For #122

### CODE REVIEW

**Review by mike-kaufman — APPROVED** [review]

**Comment by mike-kaufman** [comment]
lgtm

**Comment by legomushroom** [comment]
Code lgtm, but the labels don't look very aligned, something is off with them:

hud

**Comment by davidkpiano** [comment]
@legomushroom Fixed:
screen shot 2017-06-27 at 11 13 25 am

**Comment by legomushroom** [comment]
@davidkpiano looks good 👍

**Review by legomushroom — APPROVED** [review]
LGTM

**Pull request merged**
