### PR TITLE
[expand button]: initial PR

### PR DESCRIPTION
**Pull request by legomushroom**
Adds the expand button for HUD:

hud

### CODE REVIEW

**Comment by mike-kaufman** [comment]
@davidkpiano , @philliphoff  - please review this.

**Comment by davidkpiano** [comment]
Looks great! 🚢

**Review by mike-kaufman — APPROVED** [review]
please get sign-off from David & Phil before mergingin.

**Review by davidkpiano — APPROVED** [review]

**Comment by davidkpiano** [comment]
@legomushroom If you can, can you narrow the width of the div containing the caret? (maybe by 1/2, cc. @avanderhoorn )

Otherwise looks good to me

**Comment by avanderhoorn** [comment]
Feedback on design... can we make it a bit more narrow? By about 1/3 or 1/2?

**Comment by legomushroom** [comment]
@avanderhoorn 

`1/3`:

image

image

**Comment by avanderhoorn** [comment]
Thats better! And what does 1/2 look like?

**Comment by legomushroom** [comment]
@avanderhoorn 

`1/2`:

image

image

**Comment by avanderhoorn** [comment]
I like the last best. Can the collapsed carrot be hollow (like in VS Codes find/replace component)?

**Comment by legomushroom** [comment]
@avanderhoorn only if we are ok to pull in svg icon for that, right now we use a vanilla CSS arrow?

**Comment by mike-kaufman** [comment]
I want to land this in the next ~10 minutes to start a build, so if any styling changes are going to take longer than that, let's open separate bugs to track them.

**Comment by philliphoff** [comment]
I'm not crazy about the icon choice; it's not obvious to me what the expand/collapse icon mean in this context. To me, using `+` and `-` might have been more clear, or icons that are clear arrows.  Otherwise LGTM.

**Comment by mike-kaufman** [comment]
> I'm not crazy about the icon choice; it's not obvious to me what the expand/collapse icon mean in this context. To me, using + and - might have been more clear,

This is good feedback, oleg plz open a seperate bug to track icon choice here.  I don't want to block the functionality any longer.

**Comment by davidkpiano** [comment]
> I'm not crazy about the icon choice; it's not obvious to me what the expand/collapse icon mean in this context. To me, using + and - might have been more clear, or icons that are clear arrows. 

For context, this is modeling the expand/collapse behavior and UI in VS Code (find/replace) for now, but yeah, we can revise this.

**Comment by philliphoff** [comment]
> For context, this is modeling the expand/collapse behavior and UI in VS Code (find/replace) for now, but yeah, we can revise this.

I'd say it still doesn't work great in VS Code, but at least works slightly better since it's not expanding to a large panel.  I think these icons would be more obvious:

screen shot 2017-06-27 at 11 21 52 am
screen shot 2017-06-27 at 11 21 00 am

**Comment by legomushroom** [comment]
@davidkpiano @philliphoff I created an issue to track this: https://github.com/Glimpse/Glimpse.Client.Hud/issues/133

**Pull request merged**
